#!/bin/bash

### mklink E:\SVN\js-boilerplate-gutenberg\.git\hooks\pre-commit E:\SVN\js-boilerplate-gutenberg\git-hooks\pre-commit

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
GREEN="$(tput setaf 2)"
WHITE="$(tput setaf 7)"
YELLOW="$(tput setaf 3)"
RED="$(tput setaf 1)"
BLUE="$(tput setaf 6)"
RESET_COLOR="$(tput sgr0)"

# Replace possible paths to .git hooks based on context.
DIR=${DIR//\/.git}
DIR=${DIR//\/modules/}
DIR=${DIR//\/hooks/}

cd "${DIR}" || exit 1;

function exit_reset_colors() {
    echo "${RESET_COLOR}"
    exit 1
}

function js_tests() {
    # Run JS te
    echo "${YELLOW}[pre-commit]${BLUE} Running JS Tests... ${WHITE}"

    OUTPUT=$(yarn run test --bail 2>&1)
     if [[ $? != 0 ]]; then
        echo
        echo "${BLUE}JS Tests failed. Fix the error before commit!"
        echo "${RED}$OUTPUT"
        exit_reset_colors
    fi
    echo "${YELLOW}[pre-commit]${GREEN} JS Tests Passed!${RESET_COLOR}"

}
js_tests &

function validate_ts() {
    echo "${YELLOW}[pre-commit]${BLUE} Validating TS definitions... ${WHITE}"

    OUTPUT=$(yarn run validate-ts 2>&1)
     if [[ $? != 0 ]]; then
        echo
        echo "${BLUE}TS validation failed. Fix the error before commit!"
        echo "${RED}$OUTPUT"
        exit_reset_colors
    fi
    echo "${YELLOW}[pre-commit]${GREEN} TS validation Passed!${RESET_COLOR}"

}
validate_ts &

function js_lint() {
    echo "${YELLOW}[pre-commit]${BLUE} Running JS Lint... ${WHITE}"
    OUTPUT=$(yarn lipemat-js-boilerplate lint --fix=false 2>&1)
    if [[ $? != 0 ]]; then
        echo
        echo "${BLUE}JS Lint failed. Fix the error before commit!"
        echo "${RED}$OUTPUT"
        exit_reset_colors
    fi
    echo "${YELLOW}[pre-commit]${GREEN} JS Lint Passed!${RESET_COLOR}"

}
js_lint &


# Go through each background task
# If it sent exit code 1, it failed and the result from `wait` will be false.
FAIL=0
while [[ $(jobs -p | wc -l) -gt 0 ]]; do
    wait -n || (( FAIL+=1 ))
done

# If any of the background tasks failed, we exit 1
if [[ $FAIL -ne 0 ]]; then
    exit 1
else
    exit 0
fi
