approvedGitRepositories:
  - "https://github.com/lipemat/*"

enableGlobalCache: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 1w

pnpEnableEsmLoader: false

supportedArchitectures:
  os:
    - current
    - linux
