compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

pnpEnableEsmLoader: false

supportedArchitectures:
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-4.3.1.cjs
