yarnPath: ".yarn/releases/yarn-2.4.0.cjs"
nodeLinker: pnp
pnpMode: loose
pnpFallbackMode: all
enableScripts: false

logFilters:
  # Disable the warnings when peer dependencies are not provided due to boilerplate.
  - code: YN0002
    level: discard
  # Disable warning of third party build scripts we don't let run.
  - code: YN0004
    level: discard

