##########################################################
# Publish on npm.js
#
# @version 4.0.0
#
###########################################################

name: Publish
run-name: Publish version ${{ github.ref_name }} on npm.js.

on:
  push:
    tags:
      - "*"
      - "!*beta*"

jobs:
  publish:
    name: Publish on npm.js
    uses: lipemat/public-actions/.github/workflows/publish-package.yml@version/1
    with:
      beta: false
      nodeVersion: '20.11.0'
      withInstall: true
    secrets: inherit
